// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLog() {
  return window['go']['app']['App']['ClearLog']();
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConnectionStatus() {
  return window['go']['app']['App']['GetConnectionStatus']();
}

export function GetDevices() {
  return window['go']['app']['App']['GetDevices']();
}

export function GetMessages() {
  return window['go']['app']['App']['GetMessages']();
}

export function IsConfigEmpty() {
  return window['go']['app']['App']['IsConfigEmpty']();
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchDevices(arg1) {
  return window['go']['app']['App']['SearchDevices'](arg1);
}

export function SendCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendCommand'](arg1, arg2, arg3);
}
